In [1]:
import pandas as pd
import networkx as nx
import numpy as np
import os
import random
from scipy import sparse
from Dataset.RS_Data_Loader import RS_Data_Loader
from page_rank import pageRank
import importlib
import Support_functions.get_evaluate_data as ged

In [2]:
dataReader = RS_Data_Loader()

URM_train = dataReader.get_URM_train()
URM_validation = dataReader.get_URM_validation()
URM_test = dataReader.get_URM_test()
ICM = dataReader.get_ICM()
UCB = dataReader.get_UCM_matrix_artists()

RS_Data_Loader: loading data...
RS_Data_Loader: loading complete


In [8]:
URM_train.shape[0]

50446

## Training DataFrame construction for XGBoost

In [224]:
test_best_rec = np.argwhere(URM_train[1,:])[:10][:,1]

In [240]:
# songs of one playlist (fake) recommended
test_best_rec_list

[2018, 3368, 3373, 5024, 5630, 6056, 6209, 6560, 7545, 8050]

In [57]:
current_playlist = 1
del test_best_recc

In [117]:
# The usercontent matrix duplicated for the user of the current playlist
ucb_line = UCB[current_playlist].toarray()[0].reshape((1, -1))

In [119]:
ucb_line.shape

(1, 6668)

In [123]:
np.repeat(ucb_line, 10, axis=0)

(10, 6668)

In [154]:
# ICM for each song
ICM[test_best_rec].toarray().shape

(10, 19412)

In [127]:
res = np.concatenate([ICM[test_best_rec].toarray(), np.repeat(ucb_line, 10, axis=0)], axis=1)

In [153]:
res.shape

(10, 26080)

In [167]:
test_best_rec = test_best_rec.reshape((-1, 1))

In [170]:
test_best_rec.shape

(10, 1)

In [171]:
res = np.concatenate([test_best_rec, res], axis=1)

In [172]:
res.shape

(10, 26081)

In [205]:
user_id = 1
dict_song_pop = ged.tracks_popularity()
user_profile = URM_train.indices[
                                   URM_train.indptr[user_id]:URM_train.indptr[user_id + 1]]

# elements to add for each song

song_pop = np.array([dict_song_pop[user[0]] for user in test_best_rec.tolist()]).reshape((-1,1))
playlist_length = np.array([int(ged.lenght_playlist(user_profile))]*10).reshape((-1,1))
playlist_pop = np.array([int(ged.playlist_popularity(user_profile, pop_dict=dict_song_pop))]*10).reshape((-1,1))

In [206]:
playlist_length.shape

(10, 1)

In [212]:
user_id_array = np.array([1]*10).reshape(-1,1)

In [308]:
user_id_array.shape

(10, 1)

In [309]:
np.concatenate([np.array([1]*10).reshape(-1,1), np.array([1]*10).reshape(-1,1)], axis=0)

array([[1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1]])

In [207]:
res = np.concatenate([res, song_pop, playlist_length, playlist_pop], axis=1)

In [213]:
res = np.concatenate([res, user_id_array], axis=1)

In [214]:
res.shape

(10, 26085)

In [320]:
tracks = dataReader.tracks
tracks_duration = np.array(tracks['duration_sec']).reshape((-1,1))
tracks_duration[:,0].tolist()

[167,
 185,
 201,
 263,
 96,
 221,
 151,
 192,
 206,
 206,
 250,
 241,
 158,
 262,
 165,
 179,
 267,
 193,
 227,
 183,
 213,
 194,
 194,
 245,
 205,
 243,
 207,
 261,
 224,
 286,
 173,
 261,
 208,
 158,
 240,
 169,
 269,
 205,
 271,
 172,
 204,
 274,
 271,
 158,
 276,
 180,
 305,
 248,
 225,
 172,
 203,
 284,
 218,
 347,
 204,
 347,
 193,
 189,
 292,
 180,
 268,
 170,
 285,
 199,
 156,
 252,
 364,
 323,
 81,
 147,
 173,
 245,
 371,
 165,
 121,
 190,
 330,
 237,
 199,
 240,
 151,
 205,
 194,
 489,
 236,
 282,
 172,
 304,
 201,
 251,
 271,
 170,
 176,
 200,
 341,
 310,
 182,
 165,
 169,
 279,
 277,
 218,
 234,
 217,
 176,
 283,
 187,
 352,
 301,
 311,
 170,
 334,
 225,
 223,
 224,
 239,
 137,
 222,
 276,
 235,
 157,
 214,
 224,
 183,
 240,
 242,
 209,
 262,
 246,
 358,
 304,
 365,
 230,
 267,
 293,
 303,
 146,
 206,
 231,
 214,
 213,
 178,
 196,
 329,
 172,
 201,
 215,
 179,
 218,
 233,
 277,
 299,
 193,
 143,
 207,
 230,
 133,
 156,
 257,
 229,
 168,
 168,
 301,
 193,
 206,
 933,
 207,


In [286]:
res_new = np.concatenate([user_id_array, test_best_rec, song_pop, playlist_pop, playlist_length,
                          tracks_duration[test_best_rec_list], ICM[test_best_rec_list].toarray(),
                            np.repeat(ucb_line, 10, axis=0)], axis=1)
res_new.shape

In [301]:
res_sparse = sparse.lil_matrix(res_new, dtype=int)

In [302]:
# that's a coo matrix
res_sparse = sparse.vstack([res_sparse, res_sparse])

In [303]:
res_sparse_csc = res_sparse.tocsc()

In [307]:
df = pd.SparseDataFrame([ pd.SparseSeries(res_sparse_csc[i].toarray().ravel()) 
                                   for i in np.arange(res_sparse_csc.shape[0])])

In [305]:
df

0      1      2      3      4      5      6      7      8      9      \
0       1   2018    414    211     32    263      0      0      0      0   
1       1   3368    245    211     32    274      0      0      0      0   
2       1   3373     47    211     32    240      0      0      0      0   
3       1   5024    147    211     32    212      0      0      0      0   
4       1   5630    299    211     32    210      0      0      0      0   
5       1   6056     21    211     32    188      0      0      0      0   
6       1   6209     44    211     32    234      0      0      0      0   
7       1   6560     13    211     32    263      0      0      0      0   
8       1   7545    569    211     32    178      0      0      0      0   
9       1   8050    231    211     32    184      0      0      0      0   
10      1   2018    414    211     32    263      0      0      0      0   
11      1   3368    245    211     32    274      0      0      0      0   
12      1   3373     47    211     32    240      0      0      0      0   
13      1   5024    147    211     32    212      0      0      0      0   
14      1   5630    299    211     32    210      0      0      0      0   
15      1   6056     21    211     32    188      0      0      0      0   
16      1   6209     44    211     32    234      0      0      0      0   
17      1   6560     13    211     32    263      0      0      0      0   
18      1   7545    569    211     32    178      0      0      0      0   
19      1   8050    231    211     32    184      0      0      0      0   

    ...    26076  26077  26078  26079  26080  26081  26082  26083  26084  \
0   ...        0      0      0      0      0      0      0      0      0   
1   ...        0      0      0      0      0      0      0      0      0   
2   ...        0      0      0      0      0      0      0      0      0   
3   ...        0      0      0      0      0      0      0      0      0   
4   ...        0      0      0      0      0      0      0      0      0   
5   ...        0      0      0      0      0      0      0      0      0   
6   ...        0      0      0      0      0      0      0      0      0   
7   ...        0      0      0      0      0      0      0      0      0   
8   ...        0      0      0      0      0      0      0      0      0   
9   ...        0      0      0      0      0      0      0      0      0   
10  ...        0      0      0      0      0      0      0      0      0   
11  ...        0      0      0      0      0      0      0      0      0   
12  ...        0      0      0      0      0      0      0      0      0   
13  ...        0      0      0      0      0      0      0      0      0   
14  ...        0      0      0      0      0      0      0      0      0   
15  ...        0      0      0      0      0      0      0      0      0   
16  ...        0      0      0      0      0      0      0      0      0   
17  ...        0      0      0      0      0      0      0      0      0   
18  ...        0      0      0      0      0      0      0      0      0   
19  ...        0      0      0      0      0      0      0      0      0   

    26085  
0       0  
1       0  
2       0  
3       0  
4       0  
5       0  
6       0  
7       0  
8       0  
9       0  
10      0  
11      0  
12      0  
13      0  
14      0  
15      0  
16      0  
17      0  
18      0  
19      0  

[20 rows x 26086 columns]

In [266]:
df = pd.DataFrame(res_new, dtype=int)

In [250]:
df2 = pd.DataFrame(res_new, dtype=int)

In [267]:
df

0      1      2      3      4      5      6      7      8      9      \
0      1   2018    414    211     32      0      0      0      0      0   
1      1   3368    245    211     32      0      0      0      0      0   
2      1   3373     47    211     32      0      0      0      0      0   
3      1   5024    147    211     32      0      0      0      0      0   
4      1   5630    299    211     32      0      0      0      0      0   
5      1   6056     21    211     32      0      0      0      0      0   
6      1   6209     44    211     32      0      0      0      0      0   
7      1   6560     13    211     32      0      0      0      0      0   
8      1   7545    569    211     32      0      0      0      0      0   
9      1   8050    231    211     32      0      0      0      0      0   

   ...    26075  26076  26077  26078  26079  26080  26081  26082  26083  26084  
0  ...        0      0      0      0      0      0      0      0      0      0  
1  ...        0      0      0      0      0      0      0      0      0      0  
2  ...        0      0      0      0      0      0      0      0      0      0  
3  ...        0      0      0      0      0      0      0      0      0      0  
4  ...        0      0      0      0      0      0      0      0      0      0  
5  ...        0      0      0      0      0      0      0      0      0      0  
6  ...        0      0      0      0      0      0      0      0      0      0  
7  ...        0      0      0      0      0      0      0      0      0      0  
8  ...        0      0      0      0      0      0      0      0      0      0  
9  ...        0      0      0      0      0      0      0      0      0      0  

[10 rows x 26085 columns]

## Page Rank

In [28]:
def compute_PageRank(G, beta=0.85, epsilon=10**-4):
    '''
    Efficient computation of the PageRank values using a sparse adjacency 
    matrix and the iterative power method.
    
    Parameters
    ----------
    G : boolean adjacency matrix. np.bool8
        If the element j,i is True, means that there is a link from i to j.
    beta: 1-teleportation probability.
    epsilon: stop condition. Minimum allowed amount of change in the PageRanks
        between iterations.

    Returns
    -------
    output : tuple
        PageRank array normalized top one.
        Number of iterations.

    '''    
    #Test adjacency matrix is OK
    n,_ = G.shape
    assert(G.shape==(n,n))
    #Constants Speed-UP
    deg_out_beta = G.sum(axis=0).T/beta #vector
    #Initialize
    ranks = np.ones((n,1))/n #vector
    time = 0
    flag = True
    while flag:        
        time +=1
        with np.errstate(divide='ignore'): # Ignore division by 0 on ranks/deg_out_beta
            new_ranks = G.dot((ranks/deg_out_beta)) #vector
        #Leaked PageRank
        new_ranks += (1-new_ranks.sum())/n
        #Stop condition
        if np.linalg.norm(ranks-new_ranks,ord=1)<=epsilon:
            flag = False        
        ranks = new_ranks
    return ranks / ranks.max()

In [69]:
importlib.reload(page_rank.py)

NameError: name 'page_rank' is not defined

In [2]:
dataReader = RS_Data_Loader()

URM_train = dataReader.get_URM_train()
URM_validation = dataReader.get_URM_validation()
URM_test = dataReader.get_URM_test()
#ICM = dataReader.get_ICM()

RS_Data_Loader: loading data...
RS_Data_Loader: loading complete


In [76]:
relation_mat = URM_train.transpose().dot(URM_train).tocsc()

In [77]:
r0 = relation_mat[0].A
r0

array([[19,  0,  0, ...,  0,  0,  0]])

In [78]:
relation_mat

<20635x20635 sparse matrix of type '<class 'numpy.int64'>'
	with 10460699 stored elements in Compressed Sparse Column format>

In [79]:
user_id = 0
songs_in_playlist = URM_train.indices[URM_train.indptr[user_id]:URM_train.indptr[user_id + 1]]

In [80]:
l = range(URM_train.shape[1])
s_all = set(l)

In [81]:
songs_in_playlist

array([ 1220,  8360, 12844, 14301], dtype=int32)

In [82]:
s_0 = s_all - set(songs_in_playlist)

In [83]:
for i in s_0:
    relation_mat.data[relation_mat.indptr[i]:relation_mat.indptr[i+1]].fill(0)
relation_mat.eliminate_zeros()

In [111]:
%%timeit
a = compute_PageRank(relation_mat.transpose())[0]

47.5 ms ± 677 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [86]:
a[1220]

matrix([[0.02241312]])

In [118]:
b = (a / a.max()).A1

In [120]:
b

matrix([[0.0001372],
        [0.0001372],
        [0.0001372],
        ...,
        [0.0001372],
        [0.0001372],
        [0.0001372]])

In [89]:
print(b[1220], b[8360], b[12844])

[[0.11455208]] [[0.95930704]] [[0.20659116]]


In [91]:
URM_train[0] * b

matrix([[2.28045027]])

In [94]:
URM_train[0] * b

array([2.28045027])

In [108]:
URM_train = URM_train.astype(float)

In [109]:
URM_train

<50446x20635 sparse matrix of type '<class 'numpy.float64'>'
	with 949248 stored elements in Compressed Sparse Row format>

In [105]:
b[songs_in_playlist]

array([0.11455208, 0.95930704, 0.20659116, 1.        ])

In [110]:
URM_train[0].data *= b[songs_in_playlist]

In [99]:
URM_train[0].data

array([1, 1, 1, 1])

In [117]:
%%timeit
URM_train[0].data *= b[songs_in_playlist]

58.7 µs ± 4.2 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


# Creating vector to decrease non popular items

In [3]:
from Support_functions import get_evaluate_data as ged

In [6]:
d = ged.tracks_popularity()

In [9]:
songs_number = len(d)

In [14]:
popularity = np.asarray(list(d.values()))

In [16]:
sort_ind = np.argsort(-popularity)

In [18]:
sort_ind

array([ 8956, 10848,  5606, ..., 18233,  5921, 18563])

In [24]:
ls = np.linspace(1, 0, songs_number)

In [25]:
ls

array([1.00000000e+00, 9.99951536e-01, 9.99903073e-01, ...,
       9.69274014e-05, 4.84637007e-05, 0.00000000e+00])

In [36]:
gs = np.geomspace(1,10,songs_number)

In [38]:
vector = np.ones((songs_number))

In [39]:
for ind, elem in enumerate(sort_ind):
    vector[elem] /= gs[ind]

In [42]:
vector[18563]

0.1

In [12]:

def precision(recommended_items, relevant_items):
    is_relevant = np.in1d(recommended_items, relevant_items, assume_unique=True)

    precision_score = np.sum(is_relevant, dtype=np.float32) / len(is_relevant)

    return precision_score


def recall(recommended_items, relevant_items):
    is_relevant = np.in1d(recommended_items, relevant_items, assume_unique=True)

    recall_score = np.sum(is_relevant, dtype=np.float32) / relevant_items.shape[0]

    return recall_score


def MAP(recommended_items, relevant_items):
    is_relevant = np.in1d(recommended_items, relevant_items, assume_unique=True)

    # Cumulative sum: precision at 1, at 2, at 3 ...
    # noinspection PyUnresolvedReferences
    p_at_k = is_relevant * np.cumsum(is_relevant, dtype=np.float32) / (1 + np.arange(is_relevant.shape[0]))

    # noinspection PyUnresolvedReferences
    map_score = np.sum(p_at_k) / np.min([relevant_items.shape[0], is_relevant.shape[0]])

    return map_score


# all_playlist_to_predict must be the same as the submission version, just with the recommendations for all playlist
# test_songs_per_playlist could be untouched from the beginning
def evaluate_algorithm(all_playlist_to_predict, test_songs_per_playlist, users_number=50445):
    if 'playlist_id' in all_playlist_to_predict.columns:
        tmp = all_playlist_to_predict.copy()
        tmp.set_index('playlist_id', inplace=True)
        train_series = tmp.ix[:, 0]

    else:
        train_series = all_playlist_to_predict.ix[:, 0]

    cumulative_precision = 0.0
    cumulative_recall = 0.0
    cumulative_MAP = 0.0

    num_eval = 0

    for user_id in range(users_number + 1):
        if user_id in test_songs_per_playlist.index:
            relevant_items = np.asarray(test_songs_per_playlist[user_id])

            recommended_items = train_series[user_id]
            # recommended_items = [int(x) for x in recommended_items.split(" ")]
            recommended_items = np.asarray(recommended_items)
            num_eval += 1

            cumulative_precision += precision(recommended_items, relevant_items)
            cumulative_recall += recall(recommended_items, relevant_items)
            cumulative_MAP += MAP(recommended_items, relevant_items)

    cumulative_precision /= num_eval
    cumulative_recall /= num_eval
    cumulative_MAP /= num_eval

    to_print = "Recommender performance is: Precision = {:.6f}, Recall = {:.6f}, MAP = {:.6f}".format(
        cumulative_precision, cumulative_recall, cumulative_MAP)
    print(to_print)
    return to_print


def make_series(test):
    dict_train = test.groupby(test.playlist_id).track_id
    test_songs_per_playlist = pd.Series(dict_train.apply(list))
    return test_songs_per_playlist

# LightFM

In [1]:
from lightfm import LightFM
from lightfm.datasets import fetch_movielens
from lightfm.evaluation import precision_at_k

import pandas as pd
import networkx as nx
import numpy as np
import os
import random
from scipy import sparse
from Dataset.RS_Data_Loader import RS_Data_Loader
from page_rank import pageRank
import importlib
import Support_functions.get_evaluate_data as ged

In [2]:
dataReader = RS_Data_Loader()

URM_train = dataReader.get_URM_train()
URM_validation = dataReader.get_URM_validation()
URM_test = dataReader.get_URM_test()
ICM = dataReader.get_ICM()
UCM = dataReader.get_UCM_matrix_artists()

RS_Data_Loader: loading data...
RS_Data_Loader: loading complete


In [3]:
data = {}
data['train'] = URM_train.tocoo()
data['test'] = URM_test.tocoo()
data['item_labels'] = np.asarray(list(range(URM_train.shape[1])))
data['item_features'] = ICM
data['user_features'] = UCM

In [6]:
# Load the MovieLens 100k dataset. Only five
# star ratings are treated as positive.
data_movielens = fetch_movielens(min_rating=5.0)

In [7]:
data['item_labels']

array([    0,     1,     2, ..., 20632, 20633, 20634])

In [8]:
data['train']

<50446x20635 sparse matrix of type '<class 'numpy.int64'>'
	with 949248 stored elements in COOrdinate format>

In [7]:
# Instantiate and train the model
model = LightFM(loss='warp', no_components=100)
model.fit(data['train'], item_features=data['item_features'], user_features=data['user_features'], epochs=100, num_threads=4)

In [8]:
# Evaluate the trained model
test_precision = precision_at_k(model, data['test'], data['train'], item_features=data['item_features'], 
                                user_features=data['user_features'], k=10, num_threads=4).mean()

In [9]:
test_precision

0.04959561

In [13]:
def sample_recommendations(model, data, user_ids):
    n_users, n_items = data['train'].shape
    k = 10
    URM_test = data['test'].tocsr()
    URM_train = data['train'].tocsr()
    cumulative_MAP = 0
    for user in user_ids:
        songs_in_play = URM_train[user].indices
        scores = model.predict(user, np.arange(n_items), item_features=data['item_features'], user_features=data['user_features'])
        scores[songs_in_play] = -np.inf
        recommended_items = data['item_labels'][np.argsort(-scores)][:k]
        relevant_items = URM_test[user].indices
        
        cumulative_MAP += MAP(recommended_items, relevant_items)
        
    cumulative_MAP /= len(user_ids)
    print("MAP: {}".format(cumulative_MAP))
    

In [14]:
sample_recommendations(model, data, list(range(data['train'].shape[1])))

MAP: 0.045189817302595116
